name: "Basic Test"
on:
    pull_request:
        branches:
            - main
            
jobs:
    mocha_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.5
            - name: "Installing Dependencies"
              run: npm install
            - name: "Running Test"
              run: npm test
